### PR TITLE
Add CI using GitHub Actions

### PR DESCRIPTION
**Pull request by VKTB**
Adds CI using GitHub Actions and a status badge to the README. The status badge will start working once this PR gets merged into `master`, but this is the status badge for this branch to prove that it works:

[Build Status](https://github.com/icatproject/icat.oaipmh/actions?query=workflow%3A%22CI+Build%22)

- [x] Should run maven build
- [x] Should run integration tests
- [x] Java 8 CI should pass
- [x] Java 11 CI should pass

### CODE REVIEW

**Review by RKrahl — COMMENTED** [review]
I'm happy with the change, but have a few questions and remarks:
- I have no experience with ansible, so the question is: who is going to maintain the CI build in case of issues?
- There are several warnings on the actions [output page](https://github.com/icatproject/icat.oaipmh/actions/runs/3894658109). I guess most of them come from using deprecated macros or features in the ci-build.yml and should be easy to fix.
- Very minor: you added a task list to the PR. I guess from the output of the actions, you should tick these tasks as done.

**Comment by VKTB** [comment]
Thank you for reviewing this PR @RKrahl!

To answer your question, we are happy to maintain the CI build in case of any issues going forward. Regarding the warnings, you are right, some of them are due to using deprecated actions. I will address these warnings as part of this PR but I will also configure dependabot to check and open new PRs when new versions are released so that it automatically keeps the actions that we use updated to the latest versions.

**Comment by agbeltran** [comment]
@RKrahl are you able to review the latest changes please?

**Review by RKrahl — APPROVED** [review]
LGTM

**Pull request merged**
